### ISSUE TITLE
How to help another group?

### ISSUE THREAD

**Issue by agearhart12** [Bucknell-Biol364/Tutorial_Project_4#1]
https://github.com/Bucknell-Biol364/Tutorial_Project_4/blob/c1e240d39872f70dbf23d19a70013bcc83670482/Project01.Rmd#L34

Should we wait until after the deadline to give feedback to another group or should have it done before? 
@KField-Bucknell

**Comment by KField-Bucknell** [comment]
It will be after the deadline. I will assign a group for you to give
feedback on.
